INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-1', 'Harry Potter and the Philosopher''s Stone', 223, 'author-1');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-2', 'Moby Dick', 635, 'author-2');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-3', 'Interview with the vampire', 371, 'author-3');

INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-4', 'Carrie', 199, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-5', 'Salem''s Lot', 439, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-6', 'The Shining', 447, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-7', 'Rage', 211, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-8', 'The Stand', 823, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-9', 'The Long Walk', 384, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-10', 'The Dead Zone', 428, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-11', 'Firestarter', 426, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-12', 'Roadwork', 274, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-13', 'Cujo', 319, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-14', 'The Running Man', 219, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-15', 'The Dark Tower: The Gunslinger', 224, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-16', 'Christine', 526, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-17', 'Pet Sematary', 374, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-18', 'Cycle of the Werewolf', 127, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-19', 'The Talisman', 646, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-20', 'Thinner', 309, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-21', 'It', 1138, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-22', 'The Eyes of the Dragon', 326, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-23', 'The Dark Tower II: The Drawing of the Three', 400, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-24', 'Misery', 310, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-25', 'The Tommyknockers', 558, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-26', 'The Dark Half', 431, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-27', 'The Dark Tower III: The Waste Lands', 512, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-28', 'Needful Things', 690, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-29', 'Gerald''s Game', 352, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-30', 'Dolores Claiborne', 305, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-31', 'Insomnia', 787, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-32', 'Rose Madder', 420, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-33', 'The Green Mile', 400, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-34', 'Desperation', 704, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-35', 'The Regulators', 480, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-36', 'The Dark Tower IV: Wizard and Glass', 787, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-37', 'Bag of Bones', 529, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-38', 'The Girl Who Loved Tom Gordon', 224, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-39', 'Dreamcatcher', 620, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-40', 'Black House', 625, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-41', 'From a Buick 8', 368, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-42', 'The Dark Tower V: Wolves of the Calla', 714, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-43', 'The Dark Tower VI: Song of Susannah', 432, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-44', 'The Dark Tower VII: The Dark Tower', 845, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-45', 'The Colorado Kid', 184, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-46', 'Cell', 351, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-47', 'Lisey''s Story', 528, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-48', 'Blaze', 304, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-49', 'Duma Key', 607, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-50', 'Under the Dome', 1074, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-51', 'The Dark Tower: The Wind Through the Keyhole', 336, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-52', 'Joyland', 288, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-53', 'Doctor Sleep', 531, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-54', 'Mr. Mercedes', 436, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-55', 'Revival', 403, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-56', 'Finders Keepers', 434, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-57', 'End of Watch', 496, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-58', 'Gwendy''s Button Box', 175, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-59', 'Sleeping Beauties', 702, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-60', 'The Outsider', 576, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-61', 'Elevation', 144, 'author-4');
INSERT INTO BOOK(ID, NAME, PAGE_COUNT, AUTHOR_ID) VALUES ('book-62', 'The Institute', 576, 'author-4');
